### ISSUE TITLE
cannot download datasets after login

### ISSUE THREAD

**Issue by pcunninghamCD** [kuprel/min-dalle#18]
when running the setup script it does not seem like I can download the models from wandb
```
wandb artifact get --root=./pretrained/dalle_bart_mini dalle-mini/dalle-mini/mini-1:v0

wandb: Downloading dataset artifact dalle-mini/dalle-mini/mini-1:v0
Traceback (most recent call last):
  File "/usr/local/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wandb/cli/cli.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wandb/cli/cli.py", line 1657, in get
    path = artifact.download(root=root)
  File "/usr/local/lib/python3.9/site-packages/wandb/apis/public.py", line 3867, in download
    manifest = self._load_manifest()
  File "/usr/local/lib/python3.9/site-packages/wandb/apis/public.py", line 4135, in _load_manifest
    with requests.get(index_file_url) as req:
AttributeError: __enter__
```

**Comment by w4ffl35** [comment]
This is likely fixed
