### ISSUE TITLE
Using --torch flag results in RuntimeError exception

### ISSUE THREAD

**Issue by w4ffl35** [kuprel/min-dalle#21]
**Command run**

`python image_from_text.py --text='harry potter vampire' --torch`

**Result**

Fatal exception, unable to continue script execution.

**Error raised**

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)`

**Full stacktrace**

```
Traceback (most recent call last):
  File "image_from_text.py", line 44, in <module>
    image = generate_image_from_text(
  File "/mnt/g/Documents/Projects/min_dalle/min_dalle/generate_image.py", line 58, in generate_image_from_text
    image_tokens[:image_token_count] = generate_image_tokens_torch(
  File "/mnt/g/Documents/Projects/min_dalle/min_dalle/min_dalle_torch.py", line 89, in generate_image_tokens_torch
    encoder_state = encode_torch(
  File "/mnt/g/Documents/Projects/min_dalle/min_dalle/min_dalle_torch.py", line 40, in encode_torch
    encoder_state = encoder(text_tokens)
  File "/home/USER/envs/mindalle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/g/Documents/Projects/min_dalle/min_dalle/models/dalle_bart_encoder_torch.py", line 133, in forward
    self.embed_tokens.forward(text_tokens) +
  File "/home/USER/envs/mindalle/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/USER/envs/mindalle/lib/python3.8/site-packages/torch/nn/functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

**System environment**

- Ubuntu 20 on WSL
- python3 via venv
- Latest code on `main` branch

---

I'm guessing we need GPU specific models?

**Comment by w4ffl35** [comment]
This is no longer an issue with the latest merge
